 ---
title: "Ben_ma v0.2"
author: "Tom Payne"
date: '`r format(Sys.time(), "%Y-%m-%d %H:%M")`'
output:   
  html_document:
    toc: true
    toc_depth: 4
    number_sections: true
    toc_float: true
    theme: united
---

**Changes this version**

- Added bivariate MA

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(gridExtra)
library(ggrepel)
library(knitr)
library(kableExtra)
library(metafor)
library(lme4)
library(numDeriv)
library(BiasedUrn)
library(glue)
library(gt)
library(dmetar)
library(meta)
library(gridBase)
library(grid)
library(bayesmeta)
library(dplyr)
library(janitor)
library(brms)
library(tidybayes)
library(rjags)
library(ggridges)
library(cmdstanr)

knitr::opts_chunk$set(echo = F, message = F, warning = F, error = T, 
                      fig.height = 3, out.width = "90%", 
                      dev = "png", dpi = 300, cache = T)

### Set filepaths 
import_path_mac <- '/Users/thomaspayne/Documents/MPhil/Ben_MA/'
export_path_mac <- '/Users/thomaspayne/Documents/MPhil/Ben_MA/'

truncal2 <- read.csv(paste0(export_path_mac, "Data_Split_Multiarm_Trials 10_7_22.csv"))

#Clean Column Names
truncal2 <- truncal2 %>% 
  clean_names()

# Create Study Variable with Author and Year (dropping the 'et al.')
# I'm doing this because later I'm going to join dataframes by author names and the suffix 'et al.' was mucking this up
truncal2$author <- gsub(" et al.", "", truncal2$author)

# Generate Subgroups for Meta Analysis
truncal2 <- truncal2 %>% 
  mutate(subgroup = case_when(
    (intervention_type_intervention_1 == "Placebo") ~ "Placebo Vs Truncal Block",
    (intervention_type_intervention_1 == "Control") ~ "Control vs Truncal Block",
    (intervention_type_intervention_1 == "TEA") ~ "TEA Vs Truncal Block",
    (intervention_type_intervention_1 == "TAP") ~ "Intermittent Bolus Vs Continuous Infusion",
    (intervention_type_intervention_1 == "Wound") ~ "Wound Vs Truncal Block",
    (intervention_type_intervention_1 == "Quadratus Lumborum") ~ "Other"),
    subgroup = factor(subgroup,
                      levels = c("Control vs Truncal Block",
                                 "Placebo Vs Truncal Block",
                                 "TEA Vs Truncal Block",
                                 "Wound Vs Truncal Block",
                                 "Intermittent Bolus Vs Continuous Infusion",
                                 "Other")
    )
  )

 # Dynamic NRS at 24 Hours
dynamic_nrs_24 <- truncal2 %>% 
  dplyr::select(author, year, intervention_type_intervention_1:intervention_type_intervention_2, subgroup, n_int1, n_int2, dynamic_pain_mean_24h_int1:dynamic_pain_sd_24h_int2
  ) %>% 
  drop_na()

ome_24 <- truncal2 %>% 
  dplyr::select(author, year, intervention_type_intervention_1:intervention_type_intervention_2, subgroup, n_int1, n_int2, ome_mean_24h_int1:ome_sd_24h_int2
  ) %>% 
  drop_na()


## Use the escalc() function to calculate individual study mean differences (yi) and variance (vi)
 IVdat_dynamic_nrs_24 <-  escalc(measure = "MD", n1i = n_int2, n2i = n_int1, sd1i = dynamic_pain_sd_24h_int2, 
         sd2i = dynamic_pain_sd_24h_int1, m1i = dynamic_pain_mean_24h_int2, m2i = dynamic_pain_mean_24h_int1,
         data = dynamic_nrs_24)
 
 IVdat_ome_24 <- escalc(measure = "MD", n1i = n_int2, n2i = n_int1, sd1i = ome_sd_24h_int2, 
         sd2i = ome_sd_24h_int1, m1i = ome_mean_24h_int2, m2i = ome_mean_24h_int1,
         data = ome_24)


```

# Dynamic at 24 h
```{r dynamic_forest, fig.height=10, fig.width=13}

# First, set up priors for the brms model
# I have chosen weakly informative priors: normal for mean effect, half-Cauchy for tau

priors <- c(prior(normal(0,1), class = Intercept),
            prior(cauchy(0,0.5), class = sd))

# Now we need to create a series of functions to avoid repeating code for each subgroup
## First, the brm function

brm_fn <- function(data, subgroup_filter)  {
  dat_surg_type_fn <- data %>%
    filter(subgroup == subgroup_filter) %>%
    mutate(sei = sqrt(vi),
           author1 = paste(author, year, sep = " "))

  # Run the brms model
  m.brm <- brm(yi | se(sei) ~ 1 + (1 | author1),
               data = dat_surg_type_fn,
               prior = priors,
               iter = 4000)
  return(m.brm)
}

# Now create the forest data function - this is used for density plots

forest.data_fn <- function(m.brm) {

  # Calculate the re-weighted estimated of each study
  study.draws <- spread_draws(m.brm, r_author1[author1, ], b_Intercept) %>%
    mutate(b_Intercept = r_author1 + b_Intercept)

  # Establish the pooled result
  pooled.effect.draws <- spread_draws(m.brm, b_Intercept) %>%
    mutate(author1 = "Pooled Effect")

  # Combine the pooled result with study estimates, then play around with the lexicon (bmrs mucks this up)
  forest.data <- bind_rows(study.draws,
                           pooled.effect.draws) %>%
    ungroup() %>%
    mutate(author1 = str_replace_all(author1, "[.]", " "),
           author1 = reorder(author1, b_Intercept))
  
  return(forest.data)
}


# Now create forest.data.summary function
forest.data.summary_fn <- function(data, subgroup_filter, forest.data) {
  dat_surg_type_fn <- data %>%
    filter(subgroup == subgroup_filter) %>%
    mutate(sei = sqrt(vi),
           author1 = paste(author, year, sep = " "))
  
  # Calculate mean qi based on author1
  forest.data.summary1 <- group_by(forest.data, author1) %>%
    mean_qi(b_Intercept) 
  
  # Join the two dataframes based on similar author names
  forest.data.summary <- forest.data.summary1 %>%
    left_join(dat_surg_type_fn, by = "author1") %>%
    mutate(n_int1_tot = as.character(ifelse(author1 == "Pooled Effect",
                                    sum(dat_surg_type_fn$n_int1),
                                    n_int1)),
         n_int2_tot = as.character(ifelse(author1 == "Pooled Effect",
                                        sum(dat_surg_type_fn$n_int2),
                                        n_int2)),
           author1 = as.factor(reorder(author1, b_Intercept)))
  
  return(forest.data.summary)
}


# Finally, make the res_plot function - this will be used for columns of means, SD's, etc.

res_plot_fn <- function(forest.data.summary, subgroup_filter, shrinkage_estimate, 
                        original_estimate, truncal_n_fn, truncal_mean_sd_fn, control_n_fn, control_mean_sd_fn, m.brm) { 
    # Extract the estimates for mu and tau
  post.samples <- as_draws_df(m.brm, c("b_Intercept", "sd_author1__Intercept"))
  
  ## Create the values for shrinkage and actual effect estimates
  res_plot_pre <- forest.data.summary %>%
  mutate(weighted_effect = paste0(sprintf('%.2f', b_Intercept), 
                  ' [', sprintf('%.2f', .lower),
                  ', ', sprintf('%.2f', .upper), ']'),
         unweighted_effect = paste0(sprintf('%.2f', yi), 
                  ' [', sprintf('%.2f', yi - 1.96*sqrt(vi)),
                  ', ', sprintf('%.2f', yi + 1.96*sqrt(vi)), ']')) %>%
   mutate(unweighted_effect = ifelse(unweighted_effect == "NA [NA, NA]", 
                                   paste0("Mean τ = ", 
                                          sprintf('%.2f', mean(post.samples$sd_author1__Intercept))), unweighted_effect),
          truncal_mean_sd = paste0(sprintf('%.2f', dynamic_pain_mean_24h_int2), " (", sprintf('%.1f',dynamic_pain_sd_24h_int2), ")"),
          control_mean_sd = paste0(sprintf('%.2f', dynamic_pain_mean_24h_int1), " (", sprintf('%.1f',dynamic_pain_sd_24h_int1), ")")) %>%
    mutate(truncal_mean_sd = ifelse(truncal_mean_sd == "NA (NA)", "", truncal_mean_sd),
             control_mean_sd = ifelse(control_mean_sd == "NA (NA)", "", control_mean_sd))

# Add an additional row to the data for headings
  new_row <- data.frame(author1 = as.factor(subgroup_filter),
                      weighted_effect = shrinkage_estimate,
                      unweighted_effect = original_estimate,
                      n_int2_tot = truncal_n_fn,
                      truncal_mean_sd = truncal_mean_sd_fn,
                      n_int1_tot = control_n_fn,
                      control_mean_sd = control_mean_sd_fn)

  # Bind the new row with the previous dataframe and set the colours
  res_plot <- bind_rows(res_plot_pre, new_row) %>%
          mutate(color = ifelse(author1 == "Pooled Effect", "grey60", "black"),
                 font = ifelse(author1 == "Pooled Effect", "bold", "plain"))

  return(res_plot)
}

## Now we need to run each subgroup through all the above functions
# First, the control subgroup
# This one is a bit different because it will be the top plot, so requires a heading for each row

brm_control <- brm_fn(IVdat_dynamic_nrs_24, "Control vs Truncal Block")
## Check Rhat = 1 to ensure model convergence. Also check pp_check(m.brm_control) that posterior draws roughly approximate observed data
forest.data_control <- forest.data_fn(brm_control)
forest.data.summary_control <- forest.data.summary_fn(IVdat_dynamic_nrs_24, "Control vs Truncal Block", forest.data_control)
res_plot_control <- res_plot_fn(forest.data.summary_control, "Control vs Truncal Block", "[95%CrI]", "[95%CrI]",
                              "n", "Mean (SD)", "n", "Mean (SD)", brm_control)

## Add an extra row to res_plot_control because we need more space at the top to fit our headings in
new_row_res_plot_control <- data.frame(author1 = as.factor("Subgroup"),
                      weighted_effect = "Shrinkage MD",
                      unweighted_effect = "Observed MD",
                      n_int2_tot = "Intervention",
                      truncal_mean_sd = "",
                      n_int1_tot = "Control",
                      control_mean_sd = "",
                      color = "black",
                      font = "plain")

res_plot_control <- bind_rows(res_plot_control, new_row_res_plot_control)

# Now, the placebo subgroup
brm_placebo <- brm_fn(IVdat_dynamic_nrs_24, "Placebo Vs Truncal Block")
## Check Rhat = 1 to ensure model convergence. Also check pp_check(m.brm_placebo) that posterior draws roughly approximate observed data
forest.data_placebo <- forest.data_fn(brm_placebo)
forest.data.summary_placebo <- forest.data.summary_fn(IVdat_dynamic_nrs_24, "Placebo Vs Truncal Block", forest.data_placebo)
res_plot_placebo <- res_plot_fn(forest.data.summary_placebo, "Placebo Vs Truncal Block", "", "", "", "", "", "", brm_placebo)

# Now the TEA subgroup
brm_tea <- brm_fn(IVdat_dynamic_nrs_24, "TEA Vs Truncal Block")
## Check Rhat = 1 to ensure model convergence. Also check pp_check(m.brm_tea) that posterior draws roughly approximate observed data
forest.data_tea <- forest.data_fn(brm_tea)
forest.data.summary_tea <- forest.data.summary_fn(IVdat_dynamic_nrs_24, "TEA Vs Truncal Block", forest.data_tea)
res_plot_tea <- res_plot_fn(forest.data.summary_tea, "TEA Vs Truncal Block", "", "", "", "", "", "", brm_tea)

# Finally, the wound subgroup
brm_wound <- brm_fn(IVdat_dynamic_nrs_24, "Wound Vs Truncal Block")
forest.data_wound <- forest.data_fn(brm_wound)
forest.data.summary_wound <- forest.data.summary_fn(IVdat_dynamic_nrs_24, "Wound Vs Truncal Block", forest.data_wound)
## Check Rhat = 1 to ensure model convergence. Also check pp_check(m.brm_wound) that posterior draws roughly approximate observed data
res_plot_wound <- res_plot_fn(forest.data.summary_wound, "Wound Vs Truncal Block", "", "", "", "", "", "", brm_wound)


# Now - plotting!
## First, control subgroup plots
## The first plot is the forest plot itself with shrinkage densities for each study

p_forest_control <- ggplot(aes(b_Intercept, 
           relevel(author1, "Pooled Effect", after=Inf)), 
       data = forest.data_control) +
  # Add vertical lines for pooled effect and CI
  geom_vline(xintercept = fixef(brm_control)[1, 1], 
             color = "grey60", size = 1) +
  geom_vline(xintercept = fixef(brm_control)[1, 3:4], 
             color = "grey60", linetype = 2) +
  geom_vline(xintercept = 0, color = "black", 
             size = 1) +
  # Add densities
  geom_density_ridges(fill = "blue", 
                      rel_min_height = 0.01, 
                      col = NA, scale = 0.9,
                      alpha = 0.8) +
  geom_pointintervalh(data = forest.data.summary_control, 
                      linewidth = 1, color = "blue") +
  geom_pointintervalh(aes(xmin = yi - 1.96 * sqrt(vi), 
                          xmax = yi + 1.96 * sqrt(vi), 
                          x = yi),
                      position = position_nudge(y = -0.11),
                      data = forest.data.summary_control, 
                      linewidth = 1, 
                      col = "purple") +
  scale_x_continuous(breaks = c(-6, -4, -2, 0, 2, 4, 6), expand = c(0,0)) +
  coord_cartesian(xlim=c(-6,6), ylim=c(1,8)) +
  annotate("text", x = -3.5, y = 7.5, label = "Favours\ntruncal block", fontface = "bold") +
  annotate("text", x = 4, y = 7.5,  label = "Favours\ncontrol", fontface = "bold") +
  theme_light() +
  theme(axis.line = element_blank(),           # remove axis lines
        axis.text.x = element_blank(),         # remove x-axis tick labels
        axis.ticks.x = element_blank(),        # remove x-axis ticks
        axis.text.y = element_blank()) +
  xlab(NULL) +
  ylab(NULL)

# The second plot shows the mean + 95%CrI for observed + shrinkage effects for each study

p_estimates_control <- ggplot(aes(y = relevel(author1, "Pooled Effect", after=Inf), color = color), 
                   data = res_plot_control) +
  geom_text(aes(x = 0, label = weighted_effect), hjust = 0,
            fontface = ifelse(grepl("Shrinkage MD|\\[95%CrI\\]", res_plot_control$weighted_effect), "bold", "plain")) + 
  geom_text(aes(x = 1, label = unweighted_effect), hjust = 0, 
            fontface = ifelse(grepl("Observed MD|\\[95%CrI\\]", res_plot_control$unweighted_effect), "bold", "plain")) +
  scale_color_identity() +
  theme_void() +
  coord_cartesian(xlim = c(0, 2), ylim=c(1,8))

# The third plot shows the study name, numbers in each group, and the relevant summary statistics
p_studies_control <- ggplot(aes(y = relevel(author1, "Pooled Effect", after=Inf), color = color), 
                          data = res_plot_control) +
  geom_text(aes(x = 0, label = author1), hjust = 0, 
            fontface = ifelse(res_plot_control$author1 == "Control vs Truncal Block" | res_plot_control$author1 == "Subgroup", "bold", 
                              ifelse(res_plot_control$author1 == "Pooled Effect", "italic","plain"))) +
  geom_text(aes(x = 1.5, label = n_int2_tot), hjust = 0, 
          fontface = ifelse(res_plot_control$n_int2_tot == "Intervention" | res_plot_control$n_int2_tot == "n", "bold", "plain")) +
  geom_text(aes(x = 2, label = truncal_mean_sd), hjust = 0, 
            fontface = ifelse(res_plot_control$truncal_mean_sd == "Mean (SD)", "bold", "plain")) +
  geom_text(aes(x = 3, label = n_int1_tot), hjust = 0, 
          fontface = ifelse(res_plot_control$n_int1_tot == "Control" |  res_plot_control$n_int1_tot == "n", "bold", "plain")) +
  geom_text(aes(x = 3.5, label = control_mean_sd), hjust = 0, 
            fontface = ifelse(res_plot_control$control_mean_sd == "Mean (SD)", "bold", "plain")) +
  scale_color_identity() + # Use the specified colors directly for text color
  theme_void() +
  coord_cartesian(xlim = c(0, 4), ylim=c(1,8))


## Now, the placebo subgroup - plots are as above

p_forest_placebo <- ggplot(aes(b_Intercept, 
           relevel(author1, "Pooled Effect", after=Inf)), 
       data = forest.data_placebo) +
  # Add vertical lines for pooled effect and CI
  geom_vline(xintercept = fixef(brm_placebo)[1, 1], 
             color = "grey60", size = 1) +
  geom_vline(xintercept = fixef(brm_placebo)[1, 3:4], 
             color = "grey60", linetype = 2) +
  geom_vline(xintercept = 0, color = "black", 
             size = 1) +
  # Add densities
  geom_density_ridges(fill = "blue", 
                      rel_min_height = 0.01, 
                      col = NA, scale = 0.9,
                      alpha = 0.8) +
  geom_pointintervalh(data = forest.data.summary_placebo, 
                      linewidth = 1, color = "blue") +
  geom_pointintervalh(aes(xmin = yi - 1.96 * sqrt(vi), 
                          xmax = yi + 1.96 * sqrt(vi), 
                          x = yi),
                      position = position_nudge(y = -0.11),
                      data = forest.data.summary_placebo, 
                      linewidth = 1, 
                      col = "purple") +
  scale_x_continuous(breaks = c(-6, -4, -2, 0, 2, 4, 6), expand = c(0,0)) +
  coord_cartesian(xlim=c(-6,6), ylim=c(1,11)) +
  theme_light() +
  theme(axis.line = element_blank(),           
        axis.text.x = element_blank(),         
        axis.ticks.x = element_blank(),    
        axis.text.y = element_blank()) +
  xlab(NULL) +
  ylab(NULL)

p_estimates_placebo <- ggplot(aes(y = relevel(author1, "Pooled Effect", after=Inf), color = color), 
                   data = res_plot_placebo) +
  geom_text(aes(x = 0, label = weighted_effect), hjust = 0) + 
  geom_text(aes(x = 1, label = unweighted_effect), hjust = 0) +
  theme_void() +
  scale_color_identity() +
  coord_cartesian(xlim = c(0, 2), ylim=c(1,11))

p_studies_placebo <- ggplot(aes(y = relevel(author1, "Pooled Effect", after=Inf), color = color), 
                   data = res_plot_placebo) +
  geom_text(aes(x = 0, label = author1), hjust = 0, fontface = ifelse(res_plot_placebo$author1 == "Placebo Vs Truncal Block", "bold", 
                                                                        ifelse(res_plot_placebo$author1 == "Pooled Effect", "italic","plain"))) +
  geom_text(aes(x = 1.5, label = n_int2_tot), hjust = 0) +
  geom_text(aes(x = 2, label = truncal_mean_sd), hjust = 0) +
  geom_text(aes(x = 3, label = n_int1_tot), hjust = 0) +
  geom_text(aes(x = 3.5, label = control_mean_sd), hjust = 0) +
  theme_void() +
  scale_color_identity() +
  coord_cartesian(xlim = c(0,4))

## Now, the TEA subgroup - plot descriptions as above

p_forest_tea <- ggplot(aes(b_Intercept, 
           relevel(author1, "Pooled Effect", after=Inf)), 
       data = forest.data_tea) +
  # Add vertical lines for pooled effect and CI
  geom_vline(xintercept = fixef(brm_tea)[1, 1], 
             color = "grey60", size = 1) +
  geom_vline(xintercept = fixef(brm_tea)[1, 3:4], 
             color = "grey60", linetype = 2) +
  geom_vline(xintercept = 0, color = "black", 
             size = 1) +
  # Add densities
  geom_density_ridges(fill = "blue", 
                      rel_min_height = 0.01, 
                      col = NA, scale = 0.9,
                      alpha = 0.8) +
  geom_pointintervalh(data = forest.data.summary_tea, 
                      linewidth = 1, color = "blue") +
  geom_pointintervalh(aes(xmin = yi - 1.96 * sqrt(vi), 
                          xmax = yi + 1.96 * sqrt(vi), 
                          x = yi),
                      position = position_nudge(y = -0.11),
                      data = forest.data.summary_tea, 
                      linewidth = 1, 
                      col = "purple") +
  scale_x_continuous(breaks = c(-6, -4, -2, 0, 2, 4, 6), expand = c(0,0)) +
  coord_cartesian(xlim=c(-6,6), ylim=c(1,9)) +
  theme_light() +
  theme(axis.line = element_blank(),           
        axis.text.x = element_blank(),         
        axis.ticks.x = element_blank(),    
        axis.text.y = element_blank()) +
  xlab(NULL) +
  ylab(NULL)


p_estimates_tea <- ggplot(aes(y = relevel(author1, "Pooled Effect", after=Inf), color = color), 
                   data = res_plot_tea) +
  geom_text(aes(x = 0, label = weighted_effect), hjust = 0) + 
  geom_text(aes(x = 1, label = unweighted_effect), hjust = 0) +
  theme_void() +
  scale_color_identity() +
  coord_cartesian(xlim = c(0, 2), ylim=c(1,9))

p_studies_tea <- ggplot(aes(y = relevel(author1, "Pooled Effect", after=Inf), color = color), 
                   data = res_plot_tea) +
  geom_text(aes(x = 0, label = author1), hjust = 0, fontface = ifelse(res_plot_tea$author1 == "TEA Vs Truncal Block", "bold", 
                                                                        ifelse(res_plot_tea$author1 == "Pooled Effect", "italic","plain"))) +
  geom_text(aes(x = 1.5, label = n_int2_tot), hjust = 0) +
  geom_text(aes(x = 2, label = truncal_mean_sd), hjust = 0) +
  geom_text(aes(x = 3, label = n_int1_tot), hjust = 0) +
  geom_text(aes(x = 3.5, label = control_mean_sd), hjust = 0) +
  theme_void() +
  scale_color_identity() +
  coord_cartesian(xlim = c(0,4))

## Then, the wound subgroup - again, plots are as above

p_forest_wound <- ggplot(aes(b_Intercept, 
           relevel(author1, "Pooled Effect", after=Inf)), 
       data = forest.data_wound) +
  # Add vertical lines for pooled effect and CI
  geom_vline(xintercept = fixef(brm_wound)[1, 1], 
             color = "grey60", size = 1) +
  geom_vline(xintercept = fixef(brm_wound)[1, 3:4], 
             color = "grey60", linetype = 2) +
  geom_vline(xintercept = 0, color = "black", 
             size = 1) +
  # Add densities
  geom_density_ridges(fill = "blue", 
                      rel_min_height = 0.01, 
                      col = NA, scale = 0.9,
                      alpha = 0.8) +
  geom_pointintervalh(data = forest.data.summary_wound, 
                      linewidth = 1, color = "blue") +
  geom_pointintervalh(aes(xmin = yi - 1.96 * sqrt(vi), 
                          xmax = yi + 1.96 * sqrt(vi), 
                          x = yi),
                      position = position_nudge(y = -0.11),
                      data = forest.data.summary_wound, 
                      linewidth = 1, 
                      col = "purple") +
  scale_x_continuous(breaks = c(-6, -4, -2, 0, 2, 4, 6), expand = c(0,0)) +
  coord_cartesian(xlim=c(-6,6), ylim=c(1,5)) +
  theme_light() +
  theme(axis.line = element_blank(),           
        axis.text.x = element_blank(),         
        axis.ticks.x = element_blank(),    
        axis.text.y = element_blank()) +
  xlab(NULL) +
  ylab(NULL)


p_estimates_wound <- ggplot(aes(y = relevel(author1, "Pooled Effect", after=Inf), color = color), 
                   data = res_plot_wound) +
  geom_text(aes(x = 0, label = weighted_effect), hjust = 0) + 
  geom_text(aes(x = 1, label = unweighted_effect), hjust = 0) +
  theme_void() +
  scale_color_identity() +
  coord_cartesian(xlim = c(0, 2), ylim=c(1,5))

p_studies_wound <- ggplot(aes(y = relevel(author1, "Pooled Effect", after=Inf), color = color), 
                   data = res_plot_wound) +
  geom_text(aes(x = 0, label = author1), hjust = 0, fontface = ifelse(res_plot_wound$author1 == "Wound Vs Truncal Block", "bold", 
                                                                        ifelse(res_plot_wound$author1 == "Pooled Effect", "italic","plain"))) +
  geom_text(aes(x = 1.5, label = n_int2_tot), hjust = 0) +
  geom_text(aes(x = 2, label = truncal_mean_sd), hjust = 0) +
  geom_text(aes(x = 3, label = n_int1_tot), hjust = 0) +
  geom_text(aes(x = 3.5, label = control_mean_sd), hjust = 0) +
  theme_void() +
  scale_color_identity() +
  coord_cartesian(xlim = c(0,4))

## Finally, overall effect size 
## We must construct this separately as the functions above won't work
## I've essentially re-written the functions but scrapped all the stuff above individual studies

dat_overall <- IVdat_dynamic_nrs_24 %>%
  mutate(sei = sqrt(vi),
         author1 = paste(author,year, sep=" "))

brm_overall <- brm(yi|se(sei) ~ 1 + (1|author1),
             data = dat_overall,
             prior = priors,
             iter = 4000)

post.samples_overall <- as_draws_df(brm_overall, c("b_Intercept", "sd_author1__Intercept"))

study.draws_overall <- spread_draws(brm_overall, r_author1[author1,], b_Intercept) %>% 
  mutate(b_Intercept = r_author1 + b_Intercept)

pooled.effect.draws_overall <- spread_draws(brm_overall, b_Intercept) %>% 
  mutate(author1 = "Pooled Effect")

forest.data_overall <- pooled.effect.draws_overall %>% 
   ungroup() %>%
   mutate(author1 = str_replace_all(author1, "[.]", " ")) %>% 
   mutate(author1 = reorder(author1, b_Intercept))

forest.data.summary_overall <- group_by(forest.data_overall, author1) %>% 
  mean_qi(b_Intercept) 

res_plot <- forest.data.summary_overall %>%
  mutate(weighted_effect = paste0(sprintf('%.2f', b_Intercept), 
                  ' [', sprintf('%.2f', .lower),
                  ', ', sprintf('%.2f', .upper), ']'),
          unweighted_effect = paste0("Mean τ = ", 
                                          sprintf('%.2f', mean(post.samples_overall$sd_author1__Intercept))),
         n_int1_tot = as.character(sum(IVdat_dynamic_nrs_24$n_int1)),
         n_int2_tot = as.character(sum(IVdat_dynamic_nrs_24$n_int2)),
         truncal_mean_sd = "",
        control_mean_sd = "",
         colour = "grey60")

new_row <- data.frame(author1 = as.factor("Overall"),
                      weighted_effect = "",
                      unweighted_effect = "",
                      n_int1_tot = "",
                      n_int2_tot = "",
                      truncal_mean_sd = "",
                      control_mean_sd = "",
                      colour = "black")

res_plot_overall <- bind_rows(res_plot, new_row)

## Now make the overall plot

p_forest_overall <- ggplot(aes(b_Intercept, 
           relevel(author1, "Pooled Effect", after=Inf)), 
       data = forest.data_overall) +
  # Add vertical lines for pooled effect and CI
  geom_vline(xintercept = fixef(brm_overall)[1, 1], 
             color = "grey60", size = 1) +
  geom_vline(xintercept = fixef(brm_overall)[1, 3:4], 
             color = "grey60", linetype = 2) +
  geom_vline(xintercept = 0, color = "black", 
             size = 1) +
  # Add densities
  geom_density_ridges(fill = "blue", 
                      rel_min_height = 0.01, 
                      col = NA, scale = 0.9,
                      alpha = 0.8) +
  geom_pointintervalh(data = forest.data.summary_overall, 
                      linewidth = 1, color = "blue",
                      position = position_nudge(y = -0.11)) +
  scale_x_continuous(breaks = c(-6, -4, -2, 0, 2, 4, 6), expand = c(0,0)) +
  coord_cartesian(xlim=c(-6,6), ylim=c(1,3)) +
  theme_light() +
  theme(axis.text.y = element_blank()) +
  labs(x="Mean difference") +
  ylab(NULL)

p_estimates_overall <- ggplot(aes(y = relevel(author1, "Pooled Effect", after=Inf), colour = colour), 
                   data = res_plot_overall) +
  geom_text(aes(x = 0, label = weighted_effect), hjust = 0) + 
  geom_text(aes(x = 1, label = unweighted_effect), hjust = 0) +
  theme_void() +
  scale_color_identity() +
  coord_cartesian(xlim = c(0, 2), ylim=c(1,3))

p_studies_overall <- ggplot(aes(y = relevel(author1, "Pooled Effect", after=Inf), colour = colour), 
                   data = res_plot_overall) +
  geom_text(aes(x = 0, label = author1), hjust = 0, fontface = ifelse(res_plot_overall$author1 == "Overall", "bold",
                                                                      ifelse(res_plot_overall$author1 == "Pooled Effect", "italic","plain"))) +
  geom_text(aes(x = 1.5, label = n_int2_tot), hjust = 0) +
  geom_text(aes(x = 2, label = truncal_mean_sd), hjust = 0) +
  geom_text(aes(x = 3, label = n_int1_tot), hjust = 0) +
  geom_text(aes(x = 3.5, label = control_mean_sd), hjust = 0) +
  theme_void() +
  scale_color_identity() +
  coord_cartesian(xlim = c(0,4))

library(patchwork)

## Create a layout that we will pass to the patchwork package to size all our plots
## The vertical axis needs to be adjusted depending on the number of studies in each subgroup
layout <- c(
  area(t = 0, l = 0, b = 16, r = 45),
  area(t = 0, l = 45, b = 16, r = 65), 
  area(t = 0, l = 67, b = 16, r = 88),
  area(t = 17, l = 0, b = 36, r = 45),
  area(t = 17, l = 45, b = 36, r = 65), 
  area(t = 17, l = 67, b = 36, r = 88),
  area(t = 37, l = 0, b = 52, r = 45),
  area(t = 37, l = 45, b = 52, r = 65), 
  area(t = 37, l = 67, b = 52, r = 88),
  area(t = 53, l = 0, b = 61, r = 45),
  area(t = 53, l = 45, b = 61, r = 65), 
  area(t = 53, l = 67, b = 61, r = 88),
  area(t = 62, l = 0, b = 64, r = 45),
  area(t = 62, l = 45, b = 64, r = 65), 
  area(t = 62, l = 67, b = 64, r = 88))


# Finally, combine all the plots together
p_studies_control + p_forest_control + p_estimates_control + 
  p_studies_placebo + p_forest_placebo + p_estimates_placebo + 
  p_studies_tea + p_forest_tea + p_estimates_tea +
  p_studies_wound + p_forest_wound + p_estimates_wound +
  p_studies_overall + p_forest_overall + p_estimates_overall + plot_layout(design = layout)
```

# Bivariate MA
## Table
```{r bivariate_ma}
# First we need to change to column names to make them consistent b/w dataframes
dynamic_nrs_24_bivar <- truncal2 %>% 
  select(author, year, intervention_type_intervention_1:intervention_type_intervention_2, subgroup, n_int1, n_int2, dynamic_pain_mean_24h_int1:dynamic_pain_sd_24h_int2
  ) %>% 
  drop_na() %>%
  rename(
    m1i = dynamic_pain_mean_24h_int1,
    sd1i = dynamic_pain_sd_24h_int1,
    m2i = dynamic_pain_mean_24h_int2,
    sd2i = dynamic_pain_sd_24h_int2
  ) %>%
  mutate(outcome = "pain") # Create a column to distinguish the pain outcome from opioids

ome_24_bivar <- truncal2 %>% 
  select(author, year, intervention_type_intervention_1:intervention_type_intervention_2, subgroup, n_int1, n_int2, ome_mean_24h_int1:ome_sd_24h_int2
  ) %>% 
  drop_na() %>%
  rename(
    m1i = ome_mean_24h_int1,
    sd1i = ome_sd_24h_int1,
    m2i = ome_mean_24h_int2,
    sd2i = ome_sd_24h_int2
  ) %>%
  mutate(outcome = "opioids")  # Create a column to distinguish the opioids outcome from pain

## Bind the two dataframes together
d <- rbind(dynamic_nrs_24_bivar, ome_24_bivar)

# Calculate the mean diff for all studies
d_md <- escalc(measure = "MD", n1i = n_int2, n2i = n_int1, sd1i = sd2i, 
         sd2i = sd1i, m1i = m2i, m2i = m1i,
         data = d)

# Create 'author1' which has a different values for each individual study
d_md <- d_md %>%
  mutate(sei = sqrt(vi),
         author1 = paste(author, year, sep = " ")) %>%
  select(author1, everything(), -author, -year)

# Construct a variance-covariance matrix assuming within-study correlation = 0.5
V = metafor::vcalc(vi, cluster=author1, type=outcome, rho=0.5, data=d_md)

# Specify formula
mf <-  brms::bf(yi ~ 0 + outcome + (0 + outcome|author1) + fcor(V))

get_prior(mf, 
          data = d_md,
          data2 = list(V = V),
          family = gaussian)

# Create priors
priors =  
  prior(normal(0, 4), class = "b", coef = "outcomeopioids") +
  prior(normal(0, 4), class = "b", coef = "outcomepain") +
  prior(cauchy(0, 4), class = "sd", coef = "outcomepain", group = "author1") +
  prior(cauchy(0, 4), class = "sd", coef = "outcomeopioids", group = "author1") +
  prior(lkj(2), class = cor) +
  prior(constant(1), class = "sigma")

# Run the analysis
m1 <- brms::brm(
  formula = mf,
  prior = priors,
  data = d_md,
  data2 = list(V = V),
  family = gaussian,
  warmup = 2000, 
  iter = 4000,
  chains = 4,
  seed = 123)

#Extract medians and 95% HDIs for means/SDs for each outcome
parameters = 
  m1 |> 
  tidy_draws() |> 
  reframe("ATE: Pain" = b_outcomepain,
          "ATE: Opioid use" = b_outcomeopioids,
            
          "Tau: Pain" = sd_author1__outcomepain,
          "Tau: Opioid use" = sd_author1__outcomeopioids,
            
          "Correlation" = cor_author1__outcomeopioids__outcomepain) |> 
  pivot_longer(everything()) |> 
  group_by(name) |> 
  median_hdi(value) |> 
  mutate(across(value:.upper, ~round(., 2))) |> 
  select(-c(.width:.interval))

# Tabulate the above data
parameters |> 
  filter(str_detect(name, "ATE")) |> 
  mutate(across(-name, ~round(., 2))) |> 
  reframe(Parameter = name, 
          "Median [95% CrI]" = str_c(value, " [", .lower, ", ", .upper, "]")) |> 
  rbind(
    parameters |> 
    filter(str_detect(name, "ATE", negate = T)) |> 
    reframe(Parameter = name, 
            "Median [95% CrI]" = str_c(value, " [", .lower, ", ", .upper, "]"))
  ) |> 
  gt()

```

## Bivariate plot

```{r bivariate_ma_plot, fig.height=5, fig.width=6}
m1 |> 
  tidybayes::tidy_draws() |> 
  ggplot() +
  aes(x = b_outcomepain, y = b_outcomeopioids) +
  ggdensity::geom_hdr(
    probs = c(0.95, 0.8, 0.5),
    aes(fill = after_stat(probs)), 
    alpha = 1
  ) +
  scale_fill_manual(values = c("pink", "red", "darkred")) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_vline(xintercept = 0, linetype = 2) +
  scale_x_continuous(breaks = c(-1.5, -1, -0.5, 0, 0.5)) +
  scale_y_continuous(breaks = c(-12, -8, -4, 0, 4, 8)) +
  coord_cartesian(xlim=c(-1.2,0.5), ylim=c(-13,8)) +
  labs(x = "Mean difference in pain (dynamic NRS)",
       y = "Mean difference in opioid use (oral morphine equivalents)") +
  geom_text(aes(x = 0.1, y = 4, label = "Favours\ncontrol"), hjust = 0) +
  geom_text(aes(x = -1.2, y = -11, label = "Favours\ntruncal block"), hjust = 0) +
  ggdist::theme_ggdist()
```


# Probabilities
```{r probabilities}

prob_tbl <- m1 |> 
  tidybayes::tidy_draws() |> 
  reframe(q1 = mean(b_outcomepain < 0 & b_outcomeopioids < 0),
          q2 = mean(b_outcomepain < 0 & b_outcomeopioids > 0),
          q3 = mean(b_outcomepain > 0 & b_outcomeopioids < 0),
          q4 = mean(b_outcomepain > 0 & b_outcomeopioids > 0)) |> 
  mutate(across(everything(), ~round(., 2)))

colnames(prob_tbl) <- c("P(NRS MD < 0 & OME MD < 0)", "P(NRS MD < 0 & OME MD > 0)", "P(NRS MD > 0 & OME MD < 0)",
                        "P(NRS MD > 0 & OME MD > 0)")

kable(prob_tbl, format = "markdown", align = c("r", "r", "r", "r"))
```

# Sensitivity using other priors

```{r prior_sensitivity}
## Create priors for informative and uniform
informative_priors <- c(prior(normal(0,1), class = Intercept),
            prior(cauchy(0,0.5), class = sd))

vague_priors <- c(prior(normal(0,4), class = Intercept),
            prior(cauchy(0,4), class = sd))

turner_etal_priors <- c(prior(normal(0,4), class = Intercept),
            prior(lognormal(-1.83,1.52), class = sd))

# Now we need to create a series of functions to avoid repeating code for each subgroup
## First, the brm function


m.brm_informative <- brm(yi | se(sei) ~ 1 + (1 | author1),
               data = IVdat_dynamic_nrs_24 %>%
                 mutate(sei = sqrt(vi),
                 author1 = paste(author, year, sep = " ")),
               prior = informative_priors,
               iter = 4000,
               backend = "cmdstanr", 
               cores = parallel::detectCores(),
                chains = 4,
                seed = 123)

m.brm_vague <- update(m.brm_informative, prior = vague_priors)

m.brm_turneretal <- update(m.brm_informative, prior = turner_etal_priors)

# First make a function to extract 95% CrI's
CrI <- function(model){
  model |> 
    brms::fixef(summary = F) |>
    ggdist::median_hdi() |>
    mutate(estimate = paste0(sprintf('%.2f', y), 
                  ' [', sprintf('%.2f', ymin),
                  ', ', sprintf('%.2f', ymax), ']')) |>
    dplyr::select(estimate)
}

## The create a function for prediction intervals:

predictions = function(model){
  
  nd = data.frame(study = "new", sei = 0)
  
  set.seed(123)
  
  brms::posterior_predict(object = model,
                          newdata = nd,
                          re_formula = NULL,
                          allow_new_levels = TRUE,
                          sample_new_levels = "gaussian") |> 
    data.frame() |>
    ggdist::median_hdi() |> 
    rename(y = 1) |>
    mutate(estimate = paste0(sprintf('%.2f', y), 
                  ' [', sprintf('%.2f', .lower),
                  ', ', sprintf('%.2f', .upper), ']')) |>
    dplyr::select(estimate)
}

## Create a function for tau
#Create the text for tau
tau_text <- function(model) {
  
  posterior = 
    model |> 
    tidybayes::tidy_draws() |> 
    ggdist::median_hdi(sd_author1__Intercept) |>
    mutate(estimate = paste0(sprintf('%.2f', sd_author1__Intercept), 
                  ' [', sprintf('%.2f', .lower),
                  ', ', sprintf('%.2f', .upper), ']')) |>
    dplyr::select(estimate)
}


inform_row <- cbind(CrI(m.brm_informative), predictions(m.brm_informative), tau_text(m.brm_informative))
vague_row <- cbind(CrI(m.brm_vague), predictions(m.brm_vague), tau_text(m.brm_vague))
turneretal_row <- cbind(CrI(m.brm_turneretal), predictions(m.brm_turneretal), tau_text(m.brm_turneretal))

combined_tbl <- rbind(inform_row, vague_row, turneretal_row)

## Put row names in (corresponding to each model)
combined_tbl$model <- c("Informative",  "Vague", "Turner et al.")

## rearrange table to put models as first row
combined_tbl <- combined_tbl[c(4, 1:3)]

## Combine the dataframe into a gt()
combined_tbl %>%
  gt(rowname_col = "model") %>%
  tab_stubhead(label = "Statistical Model") %>%
  cols_label(
    estimate = "Mean difference (median [95%CrI])",
    estimate.1 = "Mean difference (median [95%CrI])",
    estimate.2 = "Median [95%CrI])") %>%
  tab_spanner(
    label = "\u03C4",
    columns = estimate.2) %>%
  tab_spanner(
    label = "Credible interval",
    columns = estimate) %>%
  tab_spanner(
    label = "Prediction interval",
    columns = estimate.1) %>%
  tab_footnote(
    footnote = paste0("\u03BC prior: ", informative_priors$prior[[1]], "; \u03C4 prior: ", informative_priors$prior[[2]]),
    locations = cells_stub(rows = model == "Informative"),
    placement = "right") %>%
  tab_footnote(
    footnote = paste0("\u03BC prior: ", vague_priors$prior[[1]], "; \u03C4 prior: ", vague_priors$prior[[2]]),
    locations = cells_stub(rows = model == "Vague"),
    placement = "right") %>%
  tab_footnote(
    footnote = paste0("\u03BC prior: ", turner_etal_priors$prior[[1]], "; \u03C4 prior: ", turner_etal_priors$prior[[2]]),
    locations = cells_stub(rows = model == "Turner et al."),
    placement = "right") %>%
  opt_footnote_marks(
    marks = "standard")
```